version: '3.9'


volumes:
  data:

services:
  db:
    image: "postgres:17.4"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    healthcheck:
      test: pg_isready --username=user --dbname=demo
      interval: 2s
      timeout: 5s
      retries: 5
